### ISSUE TITLE
Extended COC is rendered backwards

### ISSUE THREAD

**Issue by MichaelJamesParsons** [unkso/titan-app#125]
## Description
On the organizations view, the COC renders the lowest ranking extended COC member first. Reverse this order.

**Comment by ELD** [comment]
@MichaelJamesParsons This may be the culprit: https://github.com/unkso/titan-app/blob/master/titan-web-client/src/modules/organizations/components/OrganizationChainOfCommand.js#L40

**Comment by MichaelJamesParsons** [comment]
Sort of. The lists should be reversed, but the `render()` method is causing them to be reversed many times. See #126 for a summary of the fix.
