### ISSUE TITLE
As a user, I can view the member's membership history

### ISSUE THREAD

**Issue by ELD** [unkso/titan-app#36]
# Description
When I click on a member's name in the list of members in a branch, I want to be taken to a page that displays the history/file of a member of the clan.

On this page, I want to be able to see:
- The member's name
- The avatar of the member (standing in for their rank)
- Date of last forum activity
- Last date of rank (computed from file entries)
- Listing of individual entries in the user's file (similar to the static12 file)
  - In the absence of a file, just display a message that the file is empty

# Acceptance Criteria
- All the details listed above are present on the page

**Comment by MichaelJamesParsons** [comment]
## Migrate file history

```
SELECT f.id,
       file_entry_type_id as user_file_entry_type_id,
       p.user_id,
       f.start_date,
       f.end_date,
       f.comments,
       f.modified as date_modified,
       f.modified_user_id as modified_by
FROM file_entries f
INNER JOIN players p ON f.player_id = p.id;
```
