### ISSUE TITLE
As a user, I can view a searchable, paginated list of roster members.

### ISSUE THREAD

**Issue by MichaelJamesParsons** [unkso/titan-app#50]
## Description
This is by far the most requested feature missing from the present version of static12, and is simple enough to include in `v0.1`. Users should be able to view a vanilla table view of roster members. The table should be paginated, and include a single input field where members can be searched by username.

## Requirements/Expected Behavior
- Create a page `/roster` that lists all roster members.
- Table view must include pagination and a search field for looking up members by username.
- Columns should include username (including), last activity, date joined, and an icon to indicate if the member is active. Results should be sorted by username ASC by default.

**Comment by ELD** [comment]
I bumped this one to `0.1.5` in order to ship `0.1` sooner.
