### ISSUE TITLE
Look into updating webpack-dev-server dependency

### ISSUE THREAD

**Issue by ELD** [unkso/titan-app#59]
## Description

GitHub has identified as using an affected version of `webpack-dev-server` with a low severity CVE. This isn't a high priority item and doens't belong to any milestone since it only impacts dev.

See: https://github.com/unkso/titan-app/network/alert/titan-web-client/package.json/webpack-dev-server/closed

This is a major version update, so it may not be an easy upgrade. We'll tackle this when we have the bandwidth for it.

## Requirements/Expected Behavior

- `webpack-dev-server` version is 3.1.11 or later

**Comment by MichaelJamesParsons** [comment]
Resolved in #192
