### ISSUE TITLE
Automatically include file entry activities in reports

### ISSUE THREAD

**Issue by MichaelJamesParsons** [unkso/titan-app#81]
## Description
NCO's are expected to report any significant events that occur during the week (A15s, LOAs, BCT completion, promotions, etc). All of these events are already tracked as file entries. When a NCO creates a report, file entries relevant to that week should be imported so NCO's don't have to manually look them up.

## Requirements/Expected Behavior

**Comment by ELD** [comment]
@MichaelJamesParsons So what you're suggesting is that there should be an auto-populated list of file entries whose start or end dates occurred within the last week time span when the report is filed?

**Comment by MichaelJamesParsons** [comment]
Yes, this reduces a lot of work for our NCOs without a lot of effort on our part.

**Comment by MichaelJamesParsons** [comment]
Implemented in #96
