### ISSUE TITLE
Dedicated organization pages

### ISSUE THREAD

**Issue by MichaelJamesParsons** [unkso/titan-app#90]
## Description
Now that #62 has been merged, titan supports more granular organization structures. These organizations should have their own overview pages containing relevant details about the org.

## Requirements/Expected Behavior
- Change front end routes to `/organizations/{parent org id}/{child id}?`
- The page should list the organization's COC, leadership, child organizations, and standard members.

**Comment by ELD** [comment]
Closed with #91.
